micronaut:
  application:
    name: onePlanet
datasources:
  default:
    driverClassName: org.postgresql.Driver
    db-type: postgresql
netty:
  default:
    allocator:
      max-order: 3
mongodb.uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}/mydb
climatiq:
  token:
